In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('50_Startups.csv')

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
df['State']=le.fit_transform(df['State'])

In [5]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1:].values

In [6]:
x

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 2.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 1.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 2.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 1.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 2.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 0.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 1.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 2.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 0.0000000e+00],
       [1.0191308e+05, 1.1059411e+05, 2.2916095e+05, 1.0000000e+00],
       [1.0067196e+05, 9.1790610e+04, 2.4974455e+05, 0.0000000e+00],
       [9.3863750e+04, 1.2732038e+05, 2.4983944e+05, 1.0000000e+00],
       [9.1992390e+04, 1.3549507e+05, 2.5266493e+05, 0.0000000e+00],
       [1.1994324e+05, 1.5654742e+

In [7]:
ohe = OneHotEncoder()
z=ohe.fit_transform(x[:,3:4]).toarray()
x=np.delete(x,3,axis=1)
z=np.delete(z,0,axis=1)
x=np.concatenate((z,x),axis=1)

C:\Users\Sai Nidhi\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:414: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [8]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2, random_state=0)

In [9]:
xtrain

array([[1.0000000e+00, 0.0000000e+00, 5.5493950e+04, 1.0305749e+05,
        2.1463481e+05],
       [0.0000000e+00, 1.0000000e+00, 4.6014020e+04, 8.5047440e+04,
        2.0551764e+05],
       [1.0000000e+00, 0.0000000e+00, 7.5328870e+04, 1.4413598e+05,
        1.3405007e+05],
       [0.0000000e+00, 0.0000000e+00, 4.6426070e+04, 1.5769392e+05,
        2.1079767e+05],
       [1.0000000e+00, 0.0000000e+00, 9.1749160e+04, 1.1417579e+05,
        2.9491957e+05],
       [1.0000000e+00, 0.0000000e+00, 1.3029813e+05, 1.4553006e+05,
        3.2387668e+05],
       [1.0000000e+00, 0.0000000e+00, 1.1994324e+05, 1.5654742e+05,
        2.5651292e+05],
       [0.0000000e+00, 1.0000000e+00, 1.0002300e+03, 1.2415304e+05,
        1.9039300e+03],
       [0.0000000e+00, 1.0000000e+00, 5.4205000e+02, 5.1743150e+04,
        0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 6.5605480e+04, 1.5303206e+05,
        1.0713838e+05],
       [0.0000000e+00, 1.0000000e+00, 1.1452361e+05, 1.2261684e+05,
        2.61

In [10]:
xtrain.shape

(40, 5)

In [11]:
import keras
from keras.models import Sequential #initializing the neural network
from keras.layers import Dense #in creating the nn layers

Using TensorFlow backend.


In [12]:
reg = Sequential()

In [13]:
reg.add(Dense(units=5,init="random_uniform",activation='relu'))#1st layer

C:\Users\Sai Nidhi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=5, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [14]:
reg.add(Dense(units=12,init="random_uniform",activation='relu'))#2nd layer

C:\Users\Sai Nidhi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=12, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [15]:
reg.add(Dense(units=8,init="random_uniform",activation='relu')) #3rd layer

C:\Users\Sai Nidhi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=8, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [16]:
reg.add(Dense(units=1,init="random_uniform",activation='relu')) #output

C:\Users\Sai Nidhi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [17]:
reg.compile(optimizer='adam', loss='mse', metrics=['mse'])

In [22]:
reg.fit(xtrain,ytrain,batch_size=10,epochs=300)

Epoch 1/300
40/40 [==============================] - 0s 177us/step - loss: 13615995904.0000 - mean_squared_error: 13615995904.0000
Epoch 2/300
40/40 [==============================] - 0s 150us/step - loss: 13615995392.0000 - mean_squared_error: 13615995392.0000
Epoch 3/300
40/40 [==============================] - 0s 125us/step - loss: 13615995648.0000 - mean_squared_error: 13615995648.0000
Epoch 4/300
40/40 [==============================] - 0s 125us/step - loss: 13615995392.0000 - mean_squared_error: 13615995392.0000
Epoch 5/300
40/40 [==============================] - 0s 150us/step - loss: 13615996160.0000 - mean_squared_error: 13615996160.0000
Epoch 6/300
40/40 [==============================] - 0s 150us/step - loss: 13615995648.0000 - mean_squared_error: 13615995648.0000
Epoch 7/300
40/40 [==============================] - 0s 150us/step - loss: 13615995136.0000 - mean_squared_error: 13615995136.0000
Epoch 8/300
40/40 [==============================] - 0s 125us/step - loss: 13615995

40/40 [==============================] - 0s 125us/step - loss: 13615995136.0000 - mean_squared_error: 13615995136.0000
Epoch 125/300
40/40 [==============================] - 0s 175us/step - loss: 13615995648.0000 - mean_squared_error: 13615995648.0000
Epoch 126/300
40/40 [==============================] - 0s 199us/step - loss: 13615995392.0000 - mean_squared_error: 13615995392.0000
Epoch 127/300
40/40 [==============================] - 0s 199us/step - loss: 13615995392.0000 - mean_squared_error: 13615995392.0000
Epoch 128/300
40/40 [==============================] - 0s 100us/step - loss: 13615995392.0000 - mean_squared_error: 13615995392.0000
Epoch 129/300
40/40 [==============================] - 0s 150us/step - loss: 13615995648.0000 - mean_squared_error: 13615995648.0000
Epoch 130/300
40/40 [==============================] - 0s 125us/step - loss: 13615995392.0000 - mean_squared_error: 13615995392.0000
Epoch 131/300
40/40 [==============================] - 0s 150us/step - loss: 136159

40/40 [==============================] - 0s 100us/step - loss: 13615994880.0000 - mean_squared_error: 13615994880.0000
Epoch 246/300
40/40 [==============================] - 0s 125us/step - loss: 13615995904.0000 - mean_squared_error: 13615995904.0000
Epoch 247/300
40/40 [==============================] - 0s 150us/step - loss: 13615996160.0000 - mean_squared_error: 13615996160.0000
Epoch 248/300
40/40 [==============================] - 0s 175us/step - loss: 13615995392.0000 - mean_squared_error: 13615995392.0000
Epoch 249/300
40/40 [==============================] - 0s 150us/step - loss: 13615995392.0000 - mean_squared_error: 13615995392.0000
Epoch 250/300
40/40 [==============================] - 0s 150us/step - loss: 13615995648.0000 - mean_squared_error: 13615995648.0000
Epoch 251/300
40/40 [==============================] - 0s 125us/step - loss: 13615995392.0000 - mean_squared_error: 13615995392.0000
Epoch 252/300
40/40 [==============================] - 0s 100us/step - loss: 136159

In [23]:
reg.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 5)                 30        
_________________________________________________________________
dense_2 (Dense)              (None, 12)                72        
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 9         
Total params: 215
Trainable params: 215
Non-trainable params: 0
_________________________________________________________________


In [24]:
ypredreg = reg.predict(xtest)

In [25]:
from sklearn.metrics import r2_score
r2_score(ytest,ypredreg)

-11.691189733708432

In [26]:
reg.save("50_startreg.h5")

# Classification

In [27]:
df = pd.read_csv(r'F:\Programs\May4th-rsip2020-master\Navie bayes\diabetes.csv')

In [28]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age Diabetes  
0                     0.627   50      pos  
1                     0.351   31      neg  
2                     0.672   32      pos  
3                     0.167   21      neg  
4                     2.288   33      pos

In [29]:
le1=LabelEncoder()
df['Diabetes']=le1.fit_transform(df['Diabetes'])

In [30]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Diabetes  
0                     0.627   50         1  
1                     0.351   31         0  
2                     0.672   32         1  
3                     0.167   21         0  
4                     2.288   33         1

In [31]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1:].values

In [32]:
x.shape

(768, 8)

In [33]:
xtr1, xtes1, ytr1, ytes1 = train_test_split(x,y,test_size=0.2,random_state=0)

In [34]:
classifier = Sequential()

In [35]:
classifier.add(Dense(units=8 , init="random_uniform", activation="relu"))

C:\Users\Sai Nidhi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=8, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [36]:
classifier.add(Dense(units=24 , init="random_uniform", activation="relu"))

C:\Users\Sai Nidhi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=24, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [37]:
classifier.add(Dense(units=1 , init="random_uniform", activation="sigmoid"))

C:\Users\Sai Nidhi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [38]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [39]:
classifier.fit(xtr1,ytr1, epochs = 200, batch_size=32)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/200
614/614 [==============================] - 0s 714us/step - loss: 0.6889 - acc: 0.6401
Epoch 2/200
614/614 [==============================] - 0s 47us/step - loss: 0.6726 - acc: 0.6401
Epoch 3/200
614/614 [==============================] - 0s 50us/step - loss: 0.6696 - acc: 0.6401
Epoch 4/200
614/614 [==============================] - 0s 58us/step - loss: 0.6651 - acc: 0.6433
Epoch 5/200
614/614 [==============================] - 0s 75us/step - loss: 0.6624 - acc: 0.6450
Epoch 6/200
614/614 [==============================] - 0s 57us/step - loss: 0.6599 - acc: 0.6352
Epoch 7/200
614/614 [==============================] - 0s 44us/step - loss: 0.6545 - acc: 0.6417
Epoch 8/200
614/614 [==============================] - 0s 39us/step - loss: 0.6496 - acc: 0.6401
Epoch 9/200
614/614 [==============================] - 0s 68us/step - loss: 0.6446 - acc: 0.6433
Epoch 10/200
614/614 [==========

614/614 [==============================] - 0s 47us/step - loss: 0.4710 - acc: 0.7866
Epoch 165/200
614/614 [==============================] - 0s 41us/step - loss: 0.4718 - acc: 0.7785
Epoch 166/200
614/614 [==============================] - 0s 37us/step - loss: 0.4647 - acc: 0.7736
Epoch 167/200
614/614 [==============================] - 0s 42us/step - loss: 0.4706 - acc: 0.7704
Epoch 168/200
614/614 [==============================] - 0s 47us/step - loss: 0.4584 - acc: 0.7915
Epoch 169/200
614/614 [==============================] - 0s 40us/step - loss: 0.4755 - acc: 0.7769
Epoch 170/200
614/614 [==============================] - 0s 32us/step - loss: 0.4638 - acc: 0.7752
Epoch 171/200
614/614 [==============================] - 0s 37us/step - loss: 0.4644 - acc: 0.7769
Epoch 172/200
614/614 [==============================] - 0s 36us/step - loss: 0.4669 - acc: 0.7769
Epoch 173/200
614/614 [==============================] - 0s 40us/step - loss: 0.4694 - acc: 0.7818
Epoch 174/200
614/614 [=

In [41]:
yclass = classifier.predict(xtes1)

In [42]:
import sklearn.metrics as metrics
fpr,tpr, tres = metrics.roc_curve(ytes1, yclass)
aucv = metrics.auc(fpr,tpr)

In [43]:
aucv

0.8490753628952078

In [49]:
yclass = (yclass>0.5)

In [50]:
yclass

array([[False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [

In [54]:
classifier.predict(np.array([[1,1,1,1,1,1,1,1]]))>0.5

array([[False]])