In [3]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv(r"C:\Users\Sai Nidhi\Desktop\SmartBridge\SIP2020\July 20 Batch\Data.csv")

In [20]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2      NaN  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [21]:
df.isnull().sum()

Country      1
Age          1
Salary       1
Purchased    0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 400.0+ bytes


In [22]:
salnan = df[df['Country']=='Germany']['Salary'].mean()

In [23]:
df['Salary'].fillna(salnan, inplace=True)

In [24]:
df.isnull().sum()

Country      1
Age          1
Salary       0
Purchased    0
dtype: int64

In [25]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

In [26]:
df.isnull().sum()

Country      1
Age          0
Salary       0
Purchased    0
dtype: int64

In [27]:
df['Country'].mode()

0    France
dtype: object

In [28]:
df['Country'].fillna(df['Country'].mode())

0     France
1      Spain
2        NaN
3      Spain
4    Germany
5     France
6      Spain
7     France
8    Germany
9     France
Name: Country, dtype: object

In [30]:
df['Country'].fillna('Germany', inplace=True)

In [31]:
df.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [32]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  83000.0       Yes

In [ ]:
#to handle the categorical data, sklearn - LabelEncoder and OneHotEncoder

In [33]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [34]:
le = LabelEncoder()

In [36]:
df['Country']=le.fit_transform(df['Country'])

In [37]:
df.head()

Country   Age   Salary Purchased
0        0  44.0  72000.0        No
1        2  27.0  48000.0       Yes
2        1  30.0  54000.0        No
3        2  38.0  61000.0        No
4        1  40.0  83000.0       Yes

In [ ]:
# France - 0, Germany - 1, Spain - 2

In [40]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [41]:
x

array([[0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [2.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [2.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 4.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [2.00000000e+00, 3.87777778e+01, 5.20000000e+04],
       [0.00000000e+00, 4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 5.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 3.70000000e+01, 6.70000000e+04]])

In [42]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [38]:
#OneHotEncoder

In [39]:
ohe = OneHotEncoder()

In [46]:
z = ohe.fit_transform(x[:,0:1]).toarray()

In [47]:
z

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [48]:
x

array([[0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [2.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [2.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 4.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [2.00000000e+00, 3.87777778e+01, 5.20000000e+04],
       [0.00000000e+00, 4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 5.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 3.70000000e+01, 6.70000000e+04]])

In [49]:
x = np.delete(x,0, axis=1)

In [50]:
x

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 8.30000000e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [51]:
x = np.concatenate((z,x),axis=1)

In [52]:
x

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [53]:
x = np.delete(x,0, axis=1)

In [54]:
x

array([[0.00000000e+00, 0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [0.00000000e+00, 1.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 4.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 0.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 3.87777778e+01, 5.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 0.00000000e+00, 5.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 0.00000000e+00, 3.70000000e+01, 6.70000000e+04]])

In [55]:
from sklearn.preprocessing import StandardScaler

In [56]:
sc = StandardScaler()

In [58]:
x = sc.fit_transform(x)

In [59]:
x

array([[-0.65465367, -0.65465367,  0.75887436,  0.50831252],
       [-0.65465367,  1.52752523, -1.71150388, -1.42811612],
       [ 1.52752523, -0.65465367, -1.27555478, -0.94400896],
       [-0.65465367,  1.52752523, -0.11302384, -0.37921728],
       [ 1.52752523, -0.65465367,  0.17760889,  1.39584231],
       [-0.65465367, -0.65465367, -0.54897294, -0.62127086],
       [-0.65465367,  1.52752523,  0.        , -1.10537801],
       [-0.65465367, -0.65465367,  1.34013983,  1.0731042 ],
       [ 1.52752523, -0.65465367,  1.63077256,  1.39584231],
       [-0.65465367, -0.65465367, -0.25834021,  0.10488988]])

In [60]:
#training and testing

In [62]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2,random_state=0)

In [63]:
df

Country        Age   Salary Purchased
0        0  44.000000  72000.0        No
1        2  27.000000  48000.0       Yes
2        1  30.000000  54000.0        No
3        2  38.000000  61000.0        No
4        1  40.000000  83000.0       Yes
5        0  35.000000  58000.0       Yes
6        2  38.777778  52000.0        No
7        0  48.000000  79000.0       Yes
8        1  50.000000  83000.0        No
9        0  37.000000  67000.0       Yes

In [64]:
xtrain

array([[ 1.52752523, -0.65465367,  0.17760889,  1.39584231],
       [-0.65465367, -0.65465367, -0.25834021,  0.10488988],
       [-0.65465367,  1.52752523, -1.71150388, -1.42811612],
       [-0.65465367,  1.52752523,  0.        , -1.10537801],
       [-0.65465367, -0.65465367,  1.34013983,  1.0731042 ],
       [-0.65465367,  1.52752523, -0.11302384, -0.37921728],
       [-0.65465367, -0.65465367,  0.75887436,  0.50831252],
       [-0.65465367, -0.65465367, -0.54897294, -0.62127086]])